name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install coverage pytest-cov
      - name: Run tests and collect coverage
        run: |
          make install
          coverage erase
          pytest --cov-report term --cov=./src tests/ --cov-report=xml
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
